### ISSUE TITLE
Dodatno testiranje za validan Datum

### ISSUE THREAD

**Issue by tarikdurmish** [p4sh4n/Sistem_Vakcinacije#1]
Kad vam ne bude mrsko jos dodatno testirajte dal dobro radi ono za validan datum
Nemojte zaboravljat pratit onaj format sa tackama "21.09.2003." inace nekad nece raditi

**Comment by p4sh4n** [comment]
Testirana provjera datuma. Falila samo prestupna godina pa sam odma dodao
